create or replace view IM_VAULT.BDV.MODEL_PORTFOLIO_WEIGHTS_SAT(
	LNK_MODEL_PORTFOLIO_WEIGHTS_HKEY,
	FROM_DATE,
	TO_DATE,
	PORTFOLIO_ID,
	FUND_ID,
	FUND_WEIGHT,
	LOAD_DATETIME
) COMMENT='NO COMMENT PROVIDED'
 as
(
  -- PLEASE TYPE VIEW DEFINITION HERE
 WITH PWSAT AS (SELECT PWSAT.*
               FROM "IM_VAULT"."RDV"."MODEL_PORTFOLIO_WEIGHTS_SAT" PWSAT
               INNER JOIN (SELECT LNK_MODEL_PORTFOLIO_WEIGHTS_HKEY, BUS_DATE, LAST_VALUE(LOAD_DATETIME) 
                           OVER (PARTITION BY LNK_MODEL_PORTFOLIO_WEIGHTS_HKEY, BUS_DATE ORDER BY LOAD_DATETIME) AS LOAD_DATETIME
               FROM "IM_VAULT"."RDV"."MODEL_PORTFOLIO_WEIGHTS_SAT") A
               ON PWSAT.LNK_MODEL_PORTFOLIO_WEIGHTS_HKEY = A.LNK_MODEL_PORTFOLIO_WEIGHTS_HKEY
               AND PWSAT.BUS_DATE = A.BUS_DATE
               AND PWSAT.LOAD_DATETIME = A.LOAD_DATETIME)
       ,PED AS(SELECT  BUS_DATE
                   ,PORTFOLIO_KEY
                   ,IFNULL(TRY_TO_DATE(LAG(PWSAT.BUS_DATE) OVER (PARTITION BY PWSAT.PORTFOLIO_KEY ORDER BY TO_DATE(PWSAT.BUS_DATE::VARCHAR,'DD/MM/YYYY') DESC)::VARCHAR,'DD/MM/YYYY')-1,'9999-12-31') AS END_DATE
            FROM "IM_VAULT"."RDV"."MODEL_PORTFOLIO_WEIGHTS_SAT" PWSAT
            GROUP BY BUS_DATE, PORTFOLIO_KEY)
, MODEL_PORTFOLIO_WEIGHTS AS(
SELECT PWSAT.LNK_MODEL_PORTFOLIO_WEIGHTS_HKEY
      ,TRY_TO_DATE(PWSAT.BUS_DATE::VARCHAR,'DD/MM/YYYY') AS FROM_DATE
      ,PED.END_DATE AS TO_DATE
      ,CAST(PWSAT.PORTFOLIO_KEY AS VARCHAR(500)) AS PORTFOLIO_ID
      ,CAST(PWSAT.FUND_GROUP_KEY AS VARCHAR(500)) AS FUND_ID
      ,CAST(PWSAT.WEIGHTING AS DECIMAL(9,2)) AS FUND_WEIGHT
      ,PWSAT.LOAD_DATETIME
FROM PWSAT
INNER JOIN (SELECT PORTFOLIO_KEY, MAX(TRY_TO_DATE(BUS_DATE::VARCHAR,'DD/MM/YYYY')) AS BUS_DATE FROM "IM_VAULT"."RDV"."MODEL_PORTFOLIO_WEIGHTS_SAT" GROUP BY PORTFOLIO_KEY) MD
ON MD.PORTFOLIO_KEY = PWSAT.PORTFOLIO_KEY
INNER JOIN PED
ON PED.PORTFOLIO_KEY = PWSAT.PORTFOLIO_KEY
AND PED.BUS_DATE = PWSAT.BUS_DATE
)
, OVR_RECORDS AS (
    SELECT *
    FROM (
        SELECT OL.H_KEY,
               OL.BUSINESS_DATE,
               OL.ATTRIBUTE_NAME,
               OL.ATTRIBUTE_VALUE,
               OL.LOAD_DATETIME,
               ROW_NUMBER() OVER (PARTITION BY OL.H_KEY, OL.BUSINESS_DATE, OL.ATTRIBUTE_NAME
                                  ORDER BY OL.LOAD_DATETIME DESC) AS "DECLARED_RANK"
        FROM IM_VAULT_DEV.REFERENCE.OVERRIDE_LOOKUP OL)
    WHERE "DECLARED_RANK" = '1'
)
SELECT  LNK_MODEL_PORTFOLIO_WEIGHTS_HKEY
        , COALESCE(MAX(CASE
                       WHEN OL.ATTRIBUTE_NAME = 'FROM_DATE'
                       THEN OL.ATTRIBUTE_VALUE END), MPW.FROM_DATE
                  ) AS "FROM_DATE"
        , COALESCE(MAX(CASE
                       WHEN OL.ATTRIBUTE_NAME = 'TO_DATE'
                       THEN OL.ATTRIBUTE_VALUE END), MPW.TO_DATE
                  ) AS "TO_DATE"
        , COALESCE(MAX(CASE
                       WHEN OL.ATTRIBUTE_NAME = 'PORTFOLIO_ID'
                       THEN OL.ATTRIBUTE_VALUE END), MPW.PORTFOLIO_ID
                  ) AS "PORTFOLIO_ID"
        , COALESCE(MAX(CASE
                       WHEN OL.ATTRIBUTE_NAME = 'FUND_ID'
                       THEN OL.ATTRIBUTE_VALUE END), MPW.FUND_ID
                  ) AS "FUND_ID"
        , COALESCE(MAX(CASE
                       WHEN OL.ATTRIBUTE_NAME = 'FUND_WEIGHT'
                       THEN OL.ATTRIBUTE_VALUE END), MPW.FUND_WEIGHT
                  ) AS "FUND_WEIGHT"
        , MPW.LOAD_DATETIME
FROM MODEL_PORTFOLIO_WEIGHTS MPW
LEFT JOIN OVR_RECORDS OL ON OL.H_KEY = MPW.LNK_MODEL_PORTFOLIO_WEIGHTS_HKEY AND
                            (OL.BUSINESS_DATE = MPW.TO_DATE OR OL.BUSINESS_DATE = MPW.FROM_DATE) AND
                            OL.ATTRIBUTE_NAME IN ('FROM_DATE'
                                                  , 'TO_DATE'
                                                  , 'PORTFOLIO_ID'
                                                  , 'FUND_ID'
                                                  , 'FUND_WEIGHT') AND
                                                  OL.LOAD_DATETIME > MPW.LOAD_DATETIME
GROUP BY MPW.LNK_MODEL_PORTFOLIO_WEIGHTS_HKEY
         , MPW.FROM_DATE
         , MPW.TO_DATE
         , MPW.PORTFOLIO_ID
         , MPW.FUND_ID
         , MPW.FUND_WEIGHT
         , MPW.LOAD_DATETIME
);