WITH FV_HUB AS(
SELECT FVH.*
FROM "IM_VAULT"."RDV"."FUND_CLASS_HUB" FVH
INNER JOIN (SELECT FUND_CLASS_HKEY, LAST_VALUE(LOAD_DATETIME) OVER (PARTITION BY FUND_CLASS_HKEY ORDER BY LOAD_DATETIME) AS LOAD_DATETIME
            FROM "IM_VAULT"."RDV"."FUND_CLASS_HUB") A
ON FVH.FUND_CLASS_HKEY = A.FUND_CLASS_HKEY
AND FVH.LOAD_DATETIME = A.LOAD_DATETIME
)
, FV_SAL AS(
SELECT FVSAL.*
FROM "IM_VAULT"."RDV"."FUND_CLASS_SAL" FVSAL
INNER JOIN (SELECT SAL_FUND_CLASS_HASH_KEY, LAST_VALUE(LOAD_DATETIME) OVER (PARTITION BY SAL_FUND_CLASS_HASH_KEY ORDER BY LOAD_DATETIME) AS LOAD_DATETIME
            FROM "IM_VAULT"."RDV"."FUND_CLASS_SAL") A
ON FVSAL.SAL_FUND_CLASS_HASH_KEY = A.SAL_FUND_CLASS_HASH_KEY
AND FVSAL.LOAD_DATETIME = A.LOAD_DATETIME
)
, FC_PERFORMANCE AS(
SELECT    FH2.FUND_CLASS_HKEY
         ,FH2.FUND_CLASS_BKEY
         ,TO_DATE(FVPS.PRICE_DATE) AS PERF_DATE
--         ,LAG(FVPS.PRICE,DATE_TRUNC('YEAR', TO_DATE(FVPS.PRICE_DATE)), DATEDIFF(DAYS,DATE_TRUNC('YEAR', TO_DATE(FVPS.PRICE_DATE)),TO_DATE(FVPS.PRICE_DATE))) OVER (PARTITION BY FVPS.CITICODE ORDER BY FVPS.PRICE_DATE)
         ,TO_DECIMAL((FVPS.PRICE / LAG(FVPS.PRICE,1) OVER (PARTITION BY FVPS.FUND_CLASS_HKEY ORDER BY FVPS.PRICE_DATE)) -1, 38,12) AS ABS_PERF_DAILY
         ,TO_DECIMAL((FVPS.PRICE / LAG(FVPS.PRICE,7) OVER (PARTITION BY FVPS.FUND_CLASS_HKEY ORDER BY FVPS.PRICE_DATE)) -1, 38,12) AS ABS_PERF_WEEKLY   
         ,TO_DECIMAL((FVPS.PRICE / LAG(FVPS.PRICE,30) OVER (PARTITION BY FVPS.FUND_CLASS_HKEY ORDER BY FVPS.PRICE_DATE)) -1, 38,12) AS ABS_PERF_M1
         ,TO_DECIMAL((FVPS.PRICE / LAG(FVPS.PRICE,90) OVER (PARTITION BY FVPS.FUND_CLASS_HKEY ORDER BY FVPS.PRICE_DATE)) -1, 38,12) AS ABS_PERF_M3
         ,TO_DECIMAL((FVPS.PRICE / LAG(FVPS.PRICE,120) OVER (PARTITION BY FVPS.FUND_CLASS_HKEY ORDER BY FVPS.PRICE_DATE)) -1, 38,12) AS ABS_PERF_M6
         ,TO_DECIMAL((FVPS.PRICE / LAG(FVPS.PRICE,365) OVER (PARTITION BY FVPS.FUND_CLASS_HKEY ORDER BY FVPS.PRICE_DATE)) -1, 38,12) AS ABS_PERF_Y1
         ,TO_DECIMAL((FVPS.PRICE / LAG(FVPS.PRICE,1095) OVER (PARTITION BY FVPS.FUND_CLASS_HKEY ORDER BY FVPS.PRICE_DATE)) -1, 38,12) AS ABS_PERF_Y3
         ,TO_DECIMAL((FVPS.PRICE / LAG(FVPS.PRICE,1825) OVER (PARTITION BY FVPS.FUND_CLASS_HKEY ORDER BY FVPS.PRICE_DATE)) -1, 38,12) AS ABS_PERF_Y5
         ,TO_DECIMAL((FVPS.PRICE / LAG(FVPS.PRICE,2555) OVER (PARTITION BY FVPS.FUND_CLASS_HKEY ORDER BY FVPS.PRICE_DATE)) -1, 38,12) AS ABS_PERF_Y7
         ,TO_DECIMAL((FVPS.PRICE / LAG(FVPS.PRICE,3650) OVER (PARTITION BY FVPS.FUND_CLASS_HKEY ORDER BY FVPS.PRICE_DATE)) -1, 38,12) AS ABS_PERF_Y10
         ,TO_DECIMAL((FVPS.PRICE / FIRST_VALUE(FVPS.PRICE) OVER (PARTITION BY FVPS.FUND_CLASS_HKEY ORDER BY FVPS.PRICE_DATE)) -1, 38,12) AS ABS_PERF_INCEPTION
         ,TO_DATE(FVPS.LOAD_DATETIME) AS LOAD_DATETIME
  FROM IM_VAULT.RDV.FUND_CLASS_FE_PRICE_SAT FVPS
  INNER JOIN FV_HUB FH
      ON FVPS.FUND_CLASS_HKEY = FH.FUND_CLASS_HKEY
  INNER JOIN FV_SAL FVS
      ON FVS.DUPLICATE_FUND_CLASS_HKEY = FH.FUND_CLASS_HKEY
  INNER JOIN FV_HUB FH2
      ON FH2.FUND_CLASS_HKEY = FVS.MASTER_FUND_CLASS_HKEY
)
, OVR_RECORDS AS (
    SELECT *
    FROM (
        SELECT OL.H_KEY,
               OL.BUSINESS_DATE,
               OL.ATTRIBUTE_NAME,
               OL.ATTRIBUTE_VALUE,
               OL.LOAD_DATETIME,
               ROW_NUMBER() OVER (PARTITION BY OL.H_KEY, OL.BUSINESS_DATE, OL.ATTRIBUTE_NAME
                                  ORDER BY OL.LOAD_DATETIME DESC) AS "DECLARED_RANK"
        FROM IM_VAULT_DEV.REFERENCE.OVERRIDE_LOOKUP OL)
    WHERE "DECLARED_RANK" = '1'
)
SELECT  FUND_CLASS_HKEY,
        FUND_CLASS_BKEY,
        PERF_DATE,
        COALESCE(MAX(CASE
                     WHEN OL.ATTRIBUTE_NAME = 'ABS_PERF_DAILY'
                     THEN OL.ATTRIBUTE_VALUE END), FCSPS.ABS_PERF_DAILY
                ) AS "ABS_PERF_DAILY",
        COALESCE(MAX(CASE
                     WHEN OL.ATTRIBUTE_NAME = 'ABS_PERF_WEEKLY'
                     THEN OL.ATTRIBUTE_VALUE END), FCSPS.ABS_PERF_WEEKLY
                ) AS "ABS_PERF_WEEKLY",
        COALESCE(MAX(CASE
                     WHEN OL.ATTRIBUTE_NAME = 'ABS_PERF_M1'
                     THEN OL.ATTRIBUTE_VALUE END), FCSPS.ABS_PERF_M1
                ) AS "ABS_PERF_M1",
        COALESCE(MAX(CASE
                     WHEN OL.ATTRIBUTE_NAME = 'ABS_PERF_M3'
                     THEN OL.ATTRIBUTE_VALUE END), FCSPS.ABS_PERF_M3
                ) AS "ABS_PERF_M3",
        COALESCE(MAX(CASE
                     WHEN OL.ATTRIBUTE_NAME = 'ABS_PERF_M6'
                     THEN OL.ATTRIBUTE_VALUE END), FCSPS.ABS_PERF_M6
                ) AS "ABS_PERF_M6",
        COALESCE(MAX(CASE
                     WHEN OL.ATTRIBUTE_NAME = 'ABS_PERF_Y1'
                     THEN OL.ATTRIBUTE_VALUE END), FCSPS.ABS_PERF_Y1
                ) AS "ABS_PERF_Y1",
        COALESCE(MAX(CASE
                     WHEN OL.ATTRIBUTE_NAME = 'ABS_PERF_Y3'
                     THEN OL.ATTRIBUTE_VALUE END), FCSPS.ABS_PERF_Y3
                ) AS "ABS_PERF_Y3",
        COALESCE(MAX(CASE
                     WHEN OL.ATTRIBUTE_NAME = 'ABS_PERF_Y5'
                     THEN OL.ATTRIBUTE_VALUE END), FCSPS.ABS_PERF_Y5
                ) AS "ABS_PERF_Y5",
        COALESCE(MAX(CASE
                     WHEN OL.ATTRIBUTE_NAME = 'ABS_PERF_Y7'
                     THEN OL.ATTRIBUTE_VALUE END), FCSPS.ABS_PERF_Y7
                ) AS "ABS_PERF_Y7",
        COALESCE(MAX(CASE
                     WHEN OL.ATTRIBUTE_NAME = 'ABS_PERF_Y10'
                     THEN OL.ATTRIBUTE_VALUE END), FCSPS.ABS_PERF_Y10
                ) AS "ABS_PERF_Y10",
        COALESCE(MAX(CASE
                     WHEN OL.ATTRIBUTE_NAME = 'ABS_PERF_INCEPTION'
                     THEN OL.ATTRIBUTE_VALUE END), FCSPS.ABS_PERF_INCEPTION
                ) AS "ABS_PERF_INCEPTION",
        FCSPS.LOAD_DATETIME
FROM FC_PERFORMANCE FCSPS
LEFT JOIN OVR_RECORDS OL ON OL.H_KEY = FCSPS.FUND_CLASS_HKEY AND
                            OL.BUSINESS_DATE = FCSPS.PERF_DATE AND
                            OL.ATTRIBUTE_NAME IN ('ABS_PERF_DAILY',
                                                  'ABS_PERF_WEEKLY',
                                                  'ABS_PERF_M1',
                                                  'ABS_PERF_M3',
                                                  'ABS_PERF_M6',
                                                  'ABS_PERF_Y1',
                                                  'ABS_PERF_Y3',
                                                  'ABS_PERF_Y5',
                                                  'ABS_PERF_Y7',
                                                  'ABS_PERF_Y10',
                                                  'ABS_PERF_INCEPTION') AND
                                                  OL.LOAD_DATETIME > FCSPS.LOAD_DATETIME
GROUP BY FCSPS.FUND_CLASS_HKEY, 
         FCSPS.FUND_CLASS_BKEY, 
         FCSPS.PERF_DATE, 
         FCSPS.ABS_PERF_DAILY,
         FCSPS.ABS_PERF_WEEKLY,
         FCSPS.ABS_PERF_M1,
         FCSPS.ABS_PERF_M3,
         FCSPS.ABS_PERF_M6,
         FCSPS.ABS_PERF_Y1,
         FCSPS.ABS_PERF_Y3,
         FCSPS.ABS_PERF_Y5,
         FCSPS.ABS_PERF_Y7,
         FCSPS.ABS_PERF_Y10,
         FCSPS.ABS_PERF_INCEPTION,
         FCSPS.LOAD_DATETIME
ORDER BY FUND_CLASS_HKEY;