create or replace view IM_VAULT_DEV.BDV.FUND_NAV_SAT_CR_DEV(
	FUND_HKEY,
	FUND_BKEY,
	BUSINESS_DATE,
	NAV_CALC_DATE,
	NET_ASSET_VALUE,
	NAV_PER_SHARE,
	NET_CAPSTOCK_SHARES_OUTSTANDING,
	LOAD_DATETIME
) COMMENT='NO COMMENT PROVIDED'
 as (
WITH FSNS_L AS(
SELECT FUND_HKEY, NAV_DATE, BUSINESS_DATE, LAST_VALUE(LOAD_DATETIME) OVER (PARTITION BY FUND_HKEY, NAV_DATE, BUSINESS_DATE ORDER BY LOAD_DATETIME) AS LOAD_DATETIME
FROM "IM_VAULT"."RDV"."FUND_SSB_NAV_SAT"
)
, FUND_NAV_SAT AS (
SELECT FH2.FUND_HKEY, FH2.FUND_BKEY
      ,TO_DATE(FSNS.BUSINESS_DATE, 'YYYY-MM-DD') AS BUSINESS_DATE
      ,TO_DATE(FSNS.NAV_DATE, 'YYYYMMDD') AS NAV_CALC_DATE
      ,TO_NUMERIC(FSNS.NET_ASSET, 38, 2) as NET_ASSET_VALUE
      ,TO_NUMERIC(FSNS.NAV, 38, 4) as NAV_PER_SHARE
      ,TO_NUMERIC(FSNS.NET_SHARES_OUTST, 38, 3) as NET_CAPSTOCK_SHARES_OUTSTANDING
      ,FSNS.LOAD_DATETIME
FROM "IM_VAULT"."RDV"."FUND_SSB_NAV_SAT" FSNS
INNER JOIN FSNS_L
ON FSNS.FUND_HKEY = FSNS_L.FUND_HKEY
AND FSNS.NAV_DATE = FSNS_L.NAV_DATE
AND FSNS.BUSINESS_DATE = FSNS_L.BUSINESS_DATE
AND FSNS.LOAD_DATETIME = FSNS_L.LOAD_DATETIME 
INNER JOIN "IM_VAULT"."RDV"."FUND_HUB" FH
ON FH.FUND_HKEY = FSNS.FUND_HKEY
INNER JOIN "IM_VAULT"."RDV"."FUND_SAL" FSAL
ON FSAL.DUPLICATE_FUND_HKEY = FH.FUND_HKEY 
INNER JOIN "IM_VAULT"."RDV"."FUND_HUB" FH2
ON FSAL.MASTER_FUND_HKEY = FH2.FUND_HKEY
)
, OVR_RECORDS AS (
    SELECT *
    FROM (
        SELECT TRIM(OL.H_KEY) AS "H_KEY",
               TRIM(OL.BUSINESS_DATE) AS "BUSINESS_DATE",
               TRIM(OL.ATTRIBUTE_NAME) AS "ATTRIBUTE_NAME",
               OL.ATTRIBUTE_VALUE,
               TRIM(OL.LOAD_DATETIME) AS "LOAD_DATETIME",
               ROW_NUMBER() OVER (PARTITION BY OL.H_KEY, OL.BUSINESS_DATE, OL.ATTRIBUTE_NAME
                                  ORDER BY OL.LOAD_DATETIME DESC) AS "DECLARED_RANK"
        FROM IM_VAULT_DEV.REFERENCE.OVERRIDE_LOOKUP OL)
    WHERE "DECLARED_RANK" = '1'
)
SELECT  FNS.FUND_HKEY
        , FNS.FUND_BKEY
        , FNS.BUSINESS_DATE
        , COALESCE(MAX(CASE
                       WHEN OL.ATTRIBUTE_NAME = 'NAV_CALC_DATE'
                       THEN OL.ATTRIBUTE_VALUE END), FNS.NAV_CALC_DATE
                  ) AS "NAV_CALC_DATE"
        , COALESCE(MAX(CASE
                       WHEN OL.ATTRIBUTE_NAME = 'NET_ASSET_VALUE'
                       THEN OL.ATTRIBUTE_VALUE END), FNS.NET_ASSET_VALUE
                  ) AS "NET_ASSET_VALUE"
        , COALESCE(MAX(CASE
                       WHEN OL.ATTRIBUTE_NAME = 'NAV_PER_SHARE'
                       THEN OL.ATTRIBUTE_VALUE END), FNS.NAV_PER_SHARE
                  ) AS "NAV_PER_SHARE"
        , COALESCE(MAX(CASE
                       WHEN OL.ATTRIBUTE_NAME = 'NET_CAPSTOCK_SHARES_OUTSTANDING'
                       THEN OL.ATTRIBUTE_VALUE END), FNS.NET_CAPSTOCK_SHARES_OUTSTANDING
                  ) AS "NET_CAPSTOCK_SHARES_OUTSTANDING"
        , FNS.LOAD_DATETIME
FROM FUND_NAV_SAT FNS
LEFT JOIN OVR_RECORDS OL ON OL.H_KEY = FNS.FUND_HKEY AND
                            (OL.BUSINESS_DATE = FNS.BUSINESS_DATE) AND
                            OL.ATTRIBUTE_NAME IN ('NAV_CALC_DATE'
                                                  , 'NET_ASSET_VALUE'
                                                  , 'NAV_PER_SHARE'
                                                  , 'NET_CAPSTOCK_SHARES_OUTSTANDING') AND
                                                  OL.LOAD_DATETIME > FNS.LOAD_DATETIME
GROUP BY FNS.FUND_HKEY
         , FNS.FUND_BKEY
         , FNS.BUSINESS_DATE
         , FNS.NAV_CALC_DATE
         , FNS.NET_ASSET_VALUE
         , FNS.NAV_PER_SHARE
         , FNS.NET_CAPSTOCK_SHARES_OUTSTANDING
         , FNS.LOAD_DATETIME
);