create or replace view IM_VAULT.BDV.FUND_CLASS_PRICE_SAT(
	FUND_CLASS_HKEY,
	FUND_CLASS_BKEY,
	PRICE_DATE,
	BID_PRICE,
	DAILY_PRICE_CHANGE,
	LOAD_DATETIME
) COMMENT='NO COMMENT PROVIDED'
 as (
WITH FV_HUB AS(
SELECT FVH.*
FROM "IM_VAULT"."RDV"."FUND_CLASS_HUB" FVH
INNER JOIN (SELECT FUND_CLASS_HKEY, LAST_VALUE(LOAD_DATETIME) OVER (PARTITION BY FUND_CLASS_HKEY ORDER BY LOAD_DATETIME) AS LOAD_DATETIME
            FROM "IM_VAULT"."RDV"."FUND_CLASS_HUB") A
ON FVH.FUND_CLASS_HKEY = A.FUND_CLASS_HKEY
AND FVH.LOAD_DATETIME = A.LOAD_DATETIME
)
, FV_SAL AS(
SELECT FVSAL.*
FROM "IM_VAULT"."RDV"."FUND_CLASS_SAL" FVSAL
INNER JOIN (SELECT SAL_FUND_CLASS_HASH_KEY, LAST_VALUE(LOAD_DATETIME) OVER (PARTITION BY SAL_FUND_CLASS_HASH_KEY ORDER BY LOAD_DATETIME) AS LOAD_DATETIME
            FROM "IM_VAULT"."RDV"."FUND_CLASS_SAL") A
ON FVSAL.SAL_FUND_CLASS_HASH_KEY = A.SAL_FUND_CLASS_HASH_KEY
AND FVSAL.LOAD_DATETIME = A.LOAD_DATETIME)
, FC_PRICE AS(
SELECT    FH2.FUND_CLASS_HKEY
         ,FH2.FUND_CLASS_BKEY
         ,TO_DATE(FVPS.PRICE_DATE) AS PRICE_DATE
         ,TO_NUMERIC(FVPS.PRICE,10,6) AS BID_PRICE
         ,TO_NUMERIC(FVPS.PRICE - FVPS2.PRICE,10,6) AS DAILY_PRICE_CHANGE
         ,TO_DATE(FVPS.LOAD_DATETIME) AS LOAD_DATETIME
  FROM IM_VAULT.RDV.FUND_CLASS_FE_PRICE_SAT FVPS
  INNER JOIN FV_HUB FH
      ON FVPS.FUND_CLASS_HKEY = FH.FUND_CLASS_HKEY
  INNER JOIN FV_SAL FVS
      ON FVS.DUPLICATE_FUND_CLASS_HKEY = FH.FUND_CLASS_HKEY
  INNER JOIN FV_HUB FH2
      ON FH2.FUND_CLASS_HKEY = FVS.MASTER_FUND_CLASS_HKEY
  INNER JOIN IM_VAULT.RDV.FUND_CLASS_FE_PRICE_SAT FVPS2
      ON FVPS.FUND_CLASS_HKEY = FVPS2.FUND_CLASS_HKEY
      AND FVPS2.PRICE_DATE = TO_DATE(DATEADD(DAY,-1,FVPS.PRICE_DATE))
)
, OVR_RECORDS AS (
    SELECT *
    FROM (
        SELECT OL.H_KEY,
               OL.BUSINESS_DATE,
               OL.ATTRIBUTE_NAME,
               OL.ATTRIBUTE_VALUE,
               OL.LOAD_DATETIME,
               ROW_NUMBER() OVER (PARTITION BY OL.H_KEY, OL.BUSINESS_DATE, OL.ATTRIBUTE_NAME
                                  ORDER BY OL.LOAD_DATETIME DESC) AS "DECLARED_RANK"
        FROM IM_VAULT_DEV.REFERENCE.OVERRIDE_LOOKUP OL)
    WHERE "DECLARED_RANK" = '1'
)
SELECT FCPS.FUND_CLASS_HKEY
       , FCPS.FUND_CLASS_BKEY
       , FCPS.PRICE_DATE
       , COALESCE(MAX(CASE
                      WHEN OL.ATTRIBUTE_NAME = 'BID_PRICE'
                      THEN OL.ATTRIBUTE_VALUE END), FCPS.BID_PRICE
                 ) AS "BID_PRICE"
       , COALESCE(MAX(CASE
                     WHEN OL.ATTRIBUTE_NAME = 'DAILY_PRICE_CHANGE'
                     THEN OL.ATTRIBUTE_VALUE END), FCPS.DAILY_PRICE_CHANGE
                 ) AS "DAILY_PRICE_CHANGE"
       , FCPS.LOAD_DATETIME
FROM IM_VAULT_DEV.BDV.FUND_CLASS_PRICE_SAT FCPS
LEFT JOIN OVR_RECORDS OL ON OL.H_KEY = FCPS.FUND_CLASS_HKEY AND
                            OL.BUSINESS_DATE = FCPS.PRICE_DATE AND
                            OL.ATTRIBUTE_NAME IN (  'BID_PRICE'
                                                  , 'DAILY_PRICE_CHANGE') AND
                                                  OL.LOAD_DATETIME > FCPS.LOAD_DATETIME
WHERE FCPS.FUND_CLASS_HKEY = '6E93585B538B3CB5B5BE1E6CFA4ECFBD' AND FCPS.PRICE_DATE = '1992-01-02'
GROUP BY FCPS.FUND_CLASS_HKEY
         , FCPS.FUND_CLASS_BKEY
         , FCPS.PRICE_DATE
         , FCPS.BID_PRICE
         , FCPS.DAILY_PRICE_CHANGE
         , FCPS.LOAD_DATETIME
);