create or replace view IM_VAULT_DEV.BDV.FUND_CLASS_SRRI_SAT_CR_DEV(
	FUND_CLASS_HKEY,
	FUND_CLASS_BKEY,
	VOLATILITY_DATE,
	SRRI,
	LOAD_DATETIME
) COMMENT='NO COMMENT PROVIDED'
 as
(
WITH FUND_SRRI AS (
SELECT FUND_CLASS_HKEY,
       FUND_CLASS_BKEY, 
       VOLALTILITY_DATE
       , CASE WHEN VOLATILITY_5Y < 0.005
                    THEN 1
              WHEN VOLATILITY_5Y >= 0.005 AND VOLATILITY_5Y <0.02
                    THEN 2
              WHEN VOLATILITY_5Y >= 0.02 AND VOLATILITY_5Y <0.05
                    THEN 3
              WHEN VOLATILITY_5Y >= 0.05 AND VOLATILITY_5Y <0.1
                    THEN 4
              WHEN VOLATILITY_5Y >= 0.1 AND VOLATILITY_5Y <0.15
                    THEN 5
              WHEN VOLATILITY_5Y >= 0.15 AND VOLATILITY_5Y <0.25
                    THEN 6
              WHEN VOLATILITY_5Y > 0.25
                    THEN 7
        END AS SRRI
       , FVVS.LOAD_DATETIME
FROM "IM_VAULT".BDV."FUND_CLASS_VOLATILITY_SAT" FVVS
WHERE DAYOFWEEK(VOLALTILITY_DATE) = 5
AND VOLATILITY_5Y IS NOT NULL
)
, OVR_RECORDS AS (
    SELECT *
    FROM (
        SELECT TRIM(OL.H_KEY) AS "H_KEY",
               TRIM(OL.BUSINESS_DATE) AS "BUSINESS_DATE",
               TRIM(OL.ATTRIBUTE_NAME) AS "ATTRIBUTE_NAME",
               OL.ATTRIBUTE_VALUE,
               TRIM(OL.LOAD_DATETIME) AS "LOAD_DATETIME",
               ROW_NUMBER() OVER (PARTITION BY OL.H_KEY, OL.BUSINESS_DATE, OL.ATTRIBUTE_NAME
                                  ORDER BY OL.LOAD_DATETIME DESC) AS "DECLARED_RANK"
        FROM IM_VAULT_DEV.REFERENCE.OVERRIDE_LOOKUP OL)
    WHERE "DECLARED_RANK" = '1'
)
SELECT  FS.FUND_CLASS_HKEY
        , FS.FUND_CLASS_BKEY
        , COALESCE(MAX(CASE
                       WHEN OL.ATTRIBUTE_NAME = 'VOLATILITY_DATE'
                       THEN OL.ATTRIBUTE_VALUE END), FS.VOLALTILITY_DATE
                  ) AS "VOLATILITY_DATE"
        , COALESCE(MAX(CASE
                       WHEN OL.ATTRIBUTE_NAME = 'SRRI'
                       THEN OL.ATTRIBUTE_VALUE END), FS.SRRI
                  ) AS "SRRI"
        , FS.LOAD_DATETIME
FROM FUND_SRRI FS
LEFT JOIN OVR_RECORDS OL ON OL.H_KEY = FS.FUND_CLASS_HKEY AND
                            (OL.BUSINESS_DATE = FS.VOLALTILITY_DATE) AND
                            OL.ATTRIBUTE_NAME IN ('VOLATILITY_DATE'
                                                  , 'SRRI') AND
                                                  OL.LOAD_DATETIME > FS.LOAD_DATETIME
GROUP BY FS.FUND_CLASS_HKEY
         , FS.FUND_CLASS_BKEY
         , FS.VOLALTILITY_DATE
         , FS.SRRI
         , FS.LOAD_DATETIME
);