WITH PERF_START AS(
SELECT FUND_CLASS_HKEY, MIN(PRICE_DATE) AS PERF_START_DATE
FROM "IM_VAULT".BDV."FUND_CLASS_PRICE_SAT"
GROUP BY FUND_CLASS_HKEY
)
, y1cte AS (
     SELECT FVPS.FUND_CLASS_HKEY
            , DAYOFWEEK(A.PERF_DATE) AS PERF_DAILY
            , STDDEV(A.ABS_PERF_WEEKLY) AS STDDEV_Y1
     FROM  IM_VAULT.BDV.FUND_CLASS_PERFORMANCE_SAT A
     INNER JOIN IM_VAULT.BDV.FUND_CLASS_PERFORMANCE_SAT FVPS ON FVPS.FUND_CLASS_HKEY = A.FUND_CLASS_HKEY
     WHERE A.PERF_DATE <= FVPS.PERF_DATE AND 
           A.PERF_DATE > DATEADD(WEEK, -52, FVPS.PERF_DATE)
)
, y3cte AS (
     SELECT FVPS.FUND_CLASS_HKEY
            , DAYOFWEEK(A.PERF_DATE) AS PERF_DAILY
            , STDDEV(A.ABS_PERF_WEEKLY) AS STDDEV_Y3
     FROM  IM_VAULT.BDV.FUND_CLASS_PERFORMANCE_SAT A
     INNER JOIN IM_VAULT.BDV.FUND_CLASS_PERFORMANCE_SAT FVPS ON FVPS.FUND_CLASS_HKEY = A.FUND_CLASS_HKEY
     WHERE A.PERF_DATE <= FVPS.PERF_DATE AND 
           A.PERF_DATE > DATEADD(WEEK, -156, FVPS.PERF_DATE)
)
SELECT
     CASE WHEN DATEDIFF(WEEK, PS.PERF_START_DATE, FVPS.PERF_DATE) >= 52 THEN STDDEV_Y1 * SQRT(52) ELSE NULL END AS "YEAR ONE"
     , CASE WHEN DATEDIFF(WEEK, PS.PERF_START_DATE, FVPS.PERF_DATE) >= 52 THEN STDDEV_Y3 * SQRT(52) ELSE NULL END AS "YEAR three"
     , FVPS.LOAD_DATETIME
FROM IM_VAULT.BDV.FUND_CLASS_PERFORMANCE_SAT FVPS
INNER JOIN IM_VAULT.BDV.PERF_START ON PS.FUND_CLASS_HKEY = FVPS.FUND_CLASS_HKEY
LEFT JOIN y1cte ON y1cte.fund_class_hkey = fvps.fund_class_hkey AND y1cte.PERF_DAILY = DAYOFWEEK(FVPS.PERF_DATE)
LEFT JOIN y3cte ON y3cte.fund_class_hkey = fvps.fund_class_hkey AND y3cte.PERF_DAILY = DAYOFWEEK(FVPS.PERF_DATE)

WITH PERF_START AS(
    SELECT FUND_CLASS_HKEY, MIN(PRICE_DATE) AS PERF_START_DATE
    FROM "IM_VAULT".BDV."FUND_CLASS_PRICE_SAT"
    GROUP BY FUND_CLASS_HKEY
)
, T_WRAPPER AS (
     SELECT A.*
            , DATEDIFF(W, PS.PERF_START_DATE, A.PERF_DATE) AS "WeekDiff"
     FROM IM_VAULT.BDV.FUND_CLASS_PERFORMANCE_SAT A
     JOIN PERF_START PS ON A.FUND_CLASS_HKEY = PS.FUND_CLASS_HKEY
)
SELECT CASE
       WHEN TW."WeekDiff" >= 52
       THEN STDDEV(FVPS.ABS_PERF_DAILY)*SQRT(52)
       ELSE NULL
       END AS "yone"
       , CASE
         WHEN TW."WeekDiff" >= 156
         THEN STDDEV(FVPS.ABS_PERF_DAILY)*SQRT(52)
         ELSE NULL
         END AS "ythree"
FROM T_WRAPPER TW
LEFT JOIN IM_VAULT.BDV.FUND_CLASS_PERFORMANCE_SAT FVPS ON TW.FUND_CLASS_HKEY = FVPS.FUND_CLASS_HKEY
                                                       AND DAYOFWEEK(FVPS.PERF_DATE) = DAYOFWEEK(TW.PERF_DATE)
                                                       AND FVPS.PERF_DATE <= TW.PERF_DATE
                                                       AND FVPS.PERF_DATE > DATEADD(W, -52, TW.PERF_DATE);







WITH PERF_START AS(
SELECT FUND_CLASS_HKEY, MIN(PRICE_DATE) AS PERF_START_DATE
FROM "IM_VAULT".BDV."FUND_CLASS_PRICE_SAT"
GROUP BY FUND_CLASS_HKEY
)
SELECT FVPS.FUND_CLASS_HKEY,FVPS.FUND_CLASS_BKEY, FVPS.PERF_DATE AS VOLALTILITY_DATE
,CASE WHEN DATEDIFF(W,PS.PERF_START_DATE, FVPS.PERF_DATE) >=52
    THEN  SQRT(
               AVG(CASE WHEN DATEDIFF(DAY, A.PERF_DATE, FVPS.PERF_DATE) <= 365
                        THEN POWER(A.ABS_PERF_WEEKLY, 2)
                        END)
                    -   POWER(AVG(CASE WHEN DATEDIFF(DAY, A.PERF_DATE, FVPS.PERF_DATE) <= 365
                                       THEN A.ABS_PERF_WEEKLY END), 2)
                  ) * SQRT(52)
  ELSE NULL
  END AS "Year_one"
,(SELECT STDDEV(A.ABS_PERF_WEEKLY)
  FROM "IM_VAULT".BDV."FUND_CLASS_PERFORMANCE_SAT" A 
  WHERE A.FUND_CLASS_HKEY = FVPS.FUND_CLASS_HKEY
  AND DAYOFWEEK(A.PERF_DATE) = DAYOFWEEK(FVPS.PERF_DATE)
  AND A.PERF_DATE <= FVPS.PERF_DATE)
--  *SQRT(ABS(DATEDIFF(W,PS.PERF_START_DATE, FVPS.PERF_DATE))) AS VOLATILITY_INCEPTION
  *SQRT(52) AS VOLATILITY_INCEPTION
,FVPS.LOAD_DATETIME
FROM "IM_VAULT".BDV."FUND_CLASS_PERFORMANCE_SAT" FVPS
INNER JOIN PERF_START PS
ON PS.FUND_CLASS_HKEY = FVPS.FUND_CLASS_HKEY;