create or replace view IM_VAULT_DEV.BDV_OVR_TEST.FUND_CLASS_SAT(
	FUND_CLASS_HKEY,
	FUND_CLASS_BKEY,
	FROM_DATE,
	TO_DATE,
	FUND_CLASS_NAME,
	UNIT_CLASS,
	DISTRIBUTION_TYPE,
	DISTRIBUTION_TYPE_SHORT,
	CURRENCY_ISO,
	CURRENCY_HEDGED_IND,
	FUND_CLASS_LAUNCHED_DATE,
	FUND_CLASS_CLOSED_DATE,
	SEDOL,
	ISIN,
	MEXID,
	CITICODE,
	FT_FUND_ID,
	FAST_ID,
	CUSIP,
	LIPPER_ID,
	STT_MCH_BASIS_IND,
	PRICING_FREQUENCY,
    HASH_DIFF,
	LOAD_DATETIME
) COMMENT='SAT relating to fund class business entities'
 as
(;;
WITH FCSAT AS (SELECT * FROM IM_VAULT.RDV.FUND_CLASS_SAT
 QUALIFY ROW_NUMBER() OVER(PARTITION BY FUND_CLASS_HKEY, BUS_DATE ORDER BY LOAD_DATETIME DESC)=1
),
WITH FUND_CLASS_SAT AS (
    SELECT  DISTINCT
         NULLIF(TO_VARCHAR(FCSAT.FUND_CLASS_HKEY), '') AS FUND_CLASS_HKEY
        ,NULLIF(TO_VARCHAR(FCSAT.FUND_CLASS_BKEY), '') AS FUND_CLASS_BKEY
        ,TRY_TO_DATE(FCSAT.BUS_DATE::VARCHAR,'YYYYMMDD') AS FROM_DATE
        ,IFNULL(TRY_TO_DATE(lag(FCSAT.BUS_DATE) OVER (PARTITION BY FCSAT.FUND_CLASS_HKEY ORDER BY TRY_TO_DATE(FCSAT.BUS_DATE::VARCHAR,'YYYYMMDD') desc)::VARCHAR,'YYYYMMDD')-1, TO_DATE('99991231', 'YYYYMMDD')) AS TO_DATE
        ,NULLIF(TO_VARCHAR(FCSAT.FUND_CLASS_NAME), '') AS FUND_CLASS_NAME
        ,NULLIF(TO_VARCHAR(FCSAT.UNIT_CLASS), '') AS UNIT_CLASS
        ,NULLIF(TO_VARCHAR(FCSAT.DISTRIBUTION_TYPE), '') AS DISTRIBUTION_TYPE
        ,NULLIF(TO_VARCHAR(FCSAT.DISTRIBUTION_TYPE_SHORT), '') AS DISTRIBUTION_TYPE_SHORT
        ,NULLIF(TO_VARCHAR(FCSAT.CURRENCY), '') AS CURRENCY_ISO
        ,TO_BOOLEAN(FCSAT.HEDGED_IND) AS CURRENCY_HEDGED_IND
        ,TRY_TO_DATE(FCSAT.FUND_CLASS_LAUNCHED_DATE::VARCHAR,'YYYYMMDD') AS FUND_CLASS_LAUNCHED_DATE
        ,TRY_TO_DATE(FCSAT.FUND_CLASS_CLOSED_DATE::VARCHAR,'YYYYMMDD') AS FUND_CLASS_CLOSED_DATE
        -- ,ASIA_CLASS_IND
        -- ,TRY_TO_DATE(DATE_LAUNCHED::VARCHAR,'DD/MM/YYYY') AS DATE_LAUNCHED
        -- ,TRY_TO_DATE(DATE_CLOSED::VARCHAR,'DD/MM/YYYY') AS DATE_CLOSED
        ,NULLIF(TO_VARCHAR(FCSAT.SEDOL), '') AS SEDOL
        ,NULLIF(TO_VARCHAR(FCSAT.ISIN), '') AS ISIN
        ,NULLIF(TO_VARCHAR(FCSAT.MEXID), '') AS MEXID
        ,NULLIF(TO_VARCHAR(FCSAT.CITICODE), '') AS CITICODE
        ,NULLIF(TO_VARCHAR(FCSAT.FT_FUND_CODE), '') AS FT_FUND_ID
        ,NULLIF(TO_VARCHAR(FCSAT.FAST_CODE), '') AS FAST_ID
        ,NULLIF(TO_VARCHAR(FCSAT.CUSIP), '') AS CUSIP
        ,NULLIF(TO_VARCHAR(FCSAT.LIPPER_CODE), '') AS LIPPER_ID
        ,NULLIF(TO_VARCHAR(FCSAT.STT_MCH_BASIS_IND), '') AS STT_MCH_BASIS_IND
        ,NULLIF(TO_VARCHAR(FCSAT.PRICING_FREQUENCY), '') AS PRINCING_FREQUENCY
        ,FCSAT.HASH_DIFF
        ,FCSAT.LOAD_DATETIME
    FROM FCSAT ORDER BY FUND_CLASS_BKEY, FROM_DATE
),
OVR_RECORDS AS (
    SELECT *
    FROM
        (
        SELECT
             HASH_DIFF
            ,OVERRIDE_TYPE
            ,BUSINESS_DATE
            ,LOAD_DATETIME
            ,ATTRIBUTE_NAME
            ,ATTRIBUTE_VALUE
            ,ROW_NUMBER() OVER (PARTITION BY HASH_DIFF, ATTRIBUTE_NAME
                                  ORDER BY LOAD_DATETIME DESC) AS "RECORD_PRIORITY"
        FROM
            IM_VAULT_DEV.NEEDED_A_PLACE.OVERRIDE_LOOKUP
        )
    WHERE "RECORD_PRIORITY" = '1'
),
EXCLUDE_CHECK AS (
    SELECT
        OVR_R.HASH_DIFF
    FROM
        OVR_RECORDS OVR_R
    WHERE OVR_R.OVERRIDE_TYPE = 'Exclude'
),
PIVOT_OVR AS (
    SELECT
        OVR_R.HASH_DIFF
        ,MAX(CASE
             WHEN OVR_R.ATTRIBUTE_NAME = 'FUND_CLASS_NAME'
             AND OVR_R.OVERRIDE_TYPE = 'Override'
             THEN OVR_R.ATTRIBUTE_VALUE END) AS OVERRIDE_FUND_CLASS_NAME
        ,MAX(CASE
             WHEN OVR_R.ATTRIBUTE_NAME = 'UNIT_CLASS'
             AND OVR_R.OVERRIDE_TYPE = 'Override'
             THEN OVR_R.ATTRIBUTE_VALUE END) AS OVERRIDE_UNIT_CLASS
        ,MAX(CASE
             WHEN OVR_R.ATTRIBUTE_NAME = 'DISTRIBUTION_TYPE'
             AND OVR_R.OVERRIDE_TYPE = 'Override'
             THEN OVR_R.ATTRIBUTE_VALUE END) AS OVERRIDE_DISTRIBUTION_TYPE
        ,MAX(CASE
             WHEN OVR_R.ATTRIBUTE_NAME = 'DISTRIBUTION_TYPE_SHORT'
             AND OVR_R.OVERRIDE_TYPE = 'Override'
             THEN OVR_R.ATTRIBUTE_VALUE END) AS OVERRIDE_DISTRIBUTION_TYPE_SHORT
        ,MAX(CASE
             WHEN OVR_R.ATTRIBUTE_NAME = 'CURRENCY_ISO'
             AND OVR_R.OVERRIDE_TYPE = 'Override'
             THEN OVR_R.ATTRIBUTE_VALUE END) AS OVERRIDE_CURRENCY_ISO
        ,MAX(CASE
             WHEN OVR_R.ATTRIBUTE_NAME = 'CURRENCY_HEDGED_IND'
             AND OVR_R.OVERRIDE_TYPE = 'Override'
             THEN OVR_R.ATTRIBUTE_VALUE END) AS OVERRIDE_CURRENCY_HEDGED_IND
        ,MAX(CASE
             WHEN OVR_R.ATTRIBUTE_NAME = 'FUND_CLASS_LAUNCHED_DATE'
             AND OVR_R.OVERRIDE_TYPE = 'Override'
             THEN OVR_R.ATTRIBUTE_VALUE END) AS OVERRIDE_FUND_CLASS_LAUNCHED_DATE
        ,MAX(CASE
             WHEN OVR_R.ATTRIBUTE_NAME = 'FUND_CLASS_CLOSED_DATE'
             AND OVR_R.OVERRIDE_TYPE = 'Override'
             THEN OVR_R.ATTRIBUTE_VALUE END) AS OVERRIDE_FUND_CLASS_CLOSED_DATE
        ,MAX(CASE
             WHEN OVR_R.ATTRIBUTE_NAME = 'SEDOL'
             AND OVR_R.OVERRIDE_TYPE = 'Override'
             THEN OVR_R.ATTRIBUTE_VALUE END) AS OVERRIDE_SEDOL
        ,MAX(CASE
             WHEN OVR_R.ATTRIBUTE_NAME = 'ISIN'
             AND OVR_R.OVERRIDE_TYPE = 'Override'
             THEN OVR_R.ATTRIBUTE_VALUE END) AS OVERRIDE_ISIN
        ,MAX(CASE
             WHEN OVR_R.ATTRIBUTE_NAME = 'MEXID'
             AND OVR_R.OVERRIDE_TYPE = 'Override'
             THEN OVR_R.ATTRIBUTE_VALUE END) AS OVERRIDE_MEXID
        ,MAX(CASE
             WHEN OVR_R.ATTRIBUTE_NAME = 'CITICODE'
             AND OVR_R.OVERRIDE_TYPE = 'Override'
             THEN OVR_R.ATTRIBUTE_VALUE END) AS OVERRIDE_CITICODE
        ,MAX(CASE
             WHEN OVR_R.ATTRIBUTE_NAME = 'FT_FUND_ID'
             AND OVR_R.OVERRIDE_TYPE = 'Override'
             THEN OVR_R.ATTRIBUTE_VALUE END) AS OVERRIDE_FT_FUND_ID
        ,MAX(CASE
             WHEN OVR_R.ATTRIBUTE_NAME = 'FAST_ID'
             AND OVR_R.OVERRIDE_TYPE = 'Override'
             THEN OVR_R.ATTRIBUTE_VALUE END) AS OVERRIDE_FAST_ID
        ,MAX(CASE
             WHEN OVR_R.ATTRIBUTE_NAME = 'CUSIP'
             AND OVR_R.OVERRIDE_TYPE = 'Override'
             THEN OVR_R.ATTRIBUTE_VALUE END) AS OVERRIDE_CUSIP
        ,MAX(CASE
             WHEN OVR_R.ATTRIBUTE_NAME = 'LIPPER_ID'
             AND OVR_R.OVERRIDE_TYPE = 'Override'
             THEN OVR_R.ATTRIBUTE_VALUE END) AS OVERRIDE_LIPPER_ID
        ,MAX(CASE
             WHEN OVR_R.ATTRIBUTE_NAME = 'STT_MCH_BASIS_IND'
             AND OVR_R.OVERRIDE_TYPE = 'Override'
             THEN OVR_R.ATTRIBUTE_VALUE END) AS OVERRIDE_STT_MCH_BASIS_IND
        ,MAX(CASE
             WHEN OVR_R.ATTRIBUTE_NAME = 'PRICING_FREQUENCY'
             AND OVR_R.OVERRIDE_TYPE = 'Override'
             THEN OVR_R.ATTRIBUTE_VALUE END) AS OVERRIDE_PRICING_FREQUENCY
        ,MAX(OVR_R.LOAD_DATETIME) AS "LOAD_DATETIME"
    FROM
        OVR_RECORDS OVR_R
    WHERE OVR_R.OVERRIDE_TYPE = 'Override'
    GROUP BY OVR_R.HASH_DIFF
)
SELECT
    FNS.FUND_WRAPPER_ID AS FUND_WRAPPER_ID
    ,FNS.FUND_WRAPPER_HKEY AS FUND_WRAPPER_HKEY
    ,FNS.BUSINESS_DATE AS BUSINESS_DATE
    ,COALESCE(CASE
              WHEN OL."OVERRIDE_FUND_CLASS_NAME" IS NOT NULL
              AND OL.LOAD_DATETIME > FNS.LOAD_DATETIME
              THEN OL."OVERRIDE_FUND_CLASS_NAME"
              ELSE NULL
              END, FNS.FUND_CLASS_NAME) AS "FUND_CLASS_NAME"
    ,COALESCE(CASE
              WHEN OL."OVERRIDE_UNIT_CLASS" IS NOT NULL
              AND OL.LOAD_DATETIME > FNS.LOAD_DATETIME
              THEN OL."OVERRIDE_UNIT_CLASS"
              ELSE NULL
              END, FNS.UNIT_CLASS) AS "UNIT_CLASS"
     ,COALESCE(CASE
              WHEN OL."OVERRIDE_DISTRIBUTION_TYPE" IS NOT NULL
              AND OL.LOAD_DATETIME > FNS.LOAD_DATETIME
              THEN OL."OVERRIDE_DISTRIBUTION_TYPE"
              ELSE NULL
              END, FNS.DISTRIBUTION_TYPE) AS "DISTRIBUTION_TYPE"
     ,COALESCE(CASE
              WHEN OL."OVERRIDE_DISTRIBUTION_TYPE_SHORT" IS NOT NULL
              AND OL.LOAD_DATETIME > FNS.LOAD_DATETIME
              THEN OL."OVERRIDE_DISTRIBUTION_TYPE_SHORT"
              ELSE NULL
              END, FNS.DISTRIBUTION_TYPE_SHORT) AS "DISTRIBUTION_TYPE_SHORT"
    ,COALESCE(CASE
              WHEN OL."OVERRIDE_CURRENCY_ISO" IS NOT NULL
              AND OL.LOAD_DATETIME > FNS.LOAD_DATETIME
              THEN OL."OVERRIDE_CURRENCY_ISO"
              ELSE NULL
              END, FNS.CURRENCY_ISO) AS "CURRENCY_ISO"
    ,COALESCE(CASE
              WHEN OL."OVERRIDE_CURRENCY_HEDGED_IND" IS NOT NULL
              AND OL.LOAD_DATETIME > FNS.LOAD_DATETIME
              THEN OL."OVERRIDE_CURRENCY_HEDGED_IND"
              ELSE NULL
              END, FNS.CURRENCY_HEDGED_IND) AS "CURRENCY_HEDGED_IND"
    ,COALESCE(CASE
              WHEN OL."OVERRIDE_FUND_CLASS_LAUNCHED_DATE" IS NOT NULL
              AND OL.LOAD_DATETIME > FNS.LOAD_DATETIME
              THEN OL."OVERRIDE_FUND_CLASS_LAUNCHED_DATE"
              ELSE NULL
              END, FNS.FUND_CLASS_LAUNCHED_DATE) AS "FUND_CLASS_LAUNCHED_DATE"
    ,COALESCE(CASE
              WHEN OL."OVERRIDE_FUND_CLASS_CLOSED_DATE" IS NOT NULL
              AND OL.LOAD_DATETIME > FNS.LOAD_DATETIME
              THEN OL."OVERRIDE_FUND_CLASS_CLOSED_DATE"
              ELSE NULL
              END, FNS.FUND_CLASS_CLOSED_DATE) AS "FUND_CLASS_CLOSED_DATE"
    ,COALESCE(CASE
              WHEN OL."OVERRIDE_SEDOL" IS NOT NULL
              AND OL.LOAD_DATETIME > FNS.LOAD_DATETIME
              THEN OL."OVERRIDE_SEDOL"
              ELSE NULL
              END, FNS.SEDOL) AS "SEDOL"
    ,COALESCE(CASE
              WHEN OL."OVERRIDE_DISTRIBUTION_TYPE_SHORT" IS NOT NULL
              AND OL.LOAD_DATETIME > FNS.LOAD_DATETIME
              THEN OL."OVERRIDE_DISTRIBUTION_TYPE_SHORT"
              ELSE NULL
              END, FNS.DISTRIBUTION_TYPE_SHORT) AS "DISTRIBUTION_TYPE_SHORT"
    ,COALESCE(CASE
              WHEN OL."OVERRIDE_DISTRIBUTION_TYPE_SHORT" IS NOT NULL
              AND OL.LOAD_DATETIME > FNS.LOAD_DATETIME
              THEN OL."OVERRIDE_DISTRIBUTION_TYPE_SHORT"
              ELSE NULL
              END, FNS.DISTRIBUTION_TYPE_SHORT) AS "DISTRIBUTION_TYPE_SHORT"
    ,COALESCE(CASE
              WHEN OL."OVERRIDE_DISTRIBUTION_TYPE_SHORT" IS NOT NULL
              AND OL.LOAD_DATETIME > FNS.LOAD_DATETIME
              THEN OL."OVERRIDE_DISTRIBUTION_TYPE_SHORT"
              ELSE NULL
              END, FNS.DISTRIBUTION_TYPE_SHORT) AS "DISTRIBUTION_TYPE_SHORT"
    ,COALESCE(CASE
              WHEN OL."OVERRIDE_DISTRIBUTION_TYPE_SHORT" IS NOT NULL
              AND OL.LOAD_DATETIME > FNS.LOAD_DATETIME
              THEN OL."OVERRIDE_DISTRIBUTION_TYPE_SHORT"
              ELSE NULL
              END, FNS.DISTRIBUTION_TYPE_SHORT) AS "DISTRIBUTION_TYPE_SHORT"
    ,FNS.LOAD_DATETIME
    ,FNS.HASH_DIFF
FROM FUND_WRAPPER_NAV_SAT FNS
LEFT JOIN
    PIVOT_OVR OL
    ON OL.HASH_DIFF = FNS.HASH_DIFF
WHERE
    FNS.HASH_DIFF NOT IN (
        SELECT
            HASH_DIFF
        FROM
            EXCLUDE_CHECK
    )


);