create or replace view IM_VAULT_DEV.BDV_OVR_TEST.SLEEVE_NAV_SAT(
	SLEEVE_ID,
	SLEEVE_HKEY,
	BUSINESS_DATE,
	NAV_CALC_DATE,
	NET_ASSET_VALUE,
	NAV_PER_SHARE,
	NET_CAPSTOCK_SHARES_OUTSTANDING,
    HASH_DIFF,
	LOAD_DATETIME
) as
(
WITH ACSLV AS(
  SELECT * 
, TRY_TO_DATE(BUS_DATE::VARCHAR,'YYYYMMDD') AS FROM_DATE
, IFNULL(TRY_TO_DATE(LAG(BUS_DATE) OVER (PARTITION BY  SLEEVE_INSIGHTS_TICKER
         ORDER BY TRY_TO_DATE(BUS_DATE::VARCHAR,'YYYYMMDD') DESC)::VARCHAR,'YYYYMMDD')-1, TO_DATE('99991231', 'YYYYMMDD')) AS TO_DATE_T
,COALESCE(NULLIF(SLEEVE_SSGS_ACCOUNT_CLOSED_DATE, ''), TO_DATE_T) TO_DATE

FROM IM_VAULT.RDV.ACCOUNT_SLEEVE_SAT
    --   QUALIFY ROW_NUMBER() OVER(PARTITION BY SLEEVE_ID ORDER BY FROM_DATE DESC)=1
 ORDER BY LNK_ACCOUNT_SLEEVE_BKEY
), 
SLV AS (
  SELECT * 
, TRY_TO_DATE(BUS_DATE::VARCHAR,'YYYYMMDD') AS FROM_DATE
, IFNULL(TRY_TO_DATE(LAG(BUS_DATE) OVER (PARTITION BY SLEEVE_HKEY 
         ORDER BY TRY_TO_DATE(BUS_DATE::VARCHAR,'YYYYMMDD') DESC)::VARCHAR,'YYYYMMDD')-1, TO_DATE('99991231', 'YYYYMMDD')) AS TO_DATE_T 
,COALESCE(NULLIF(SLEEVE_CLOSED_DATE, ''), TO_DATE_T) TO_DATE
  FROM IM_VAULT.RDV.SLEEVE_SAT ORDER BY SLEEVE_BKEY
),
SLEEVE_NAV_SAT AS (
    SELECT DISTINCT
        SLV.SLEEVE_ID AS SLEEVE_ID,
        SLV.SLEEVE_HKEY AS SLEEVE_HKEY,
        TRY_TO_DATE(NAV.BUSINESS_DATE,'YYYY-MM-DD') AS BUSINESS_DATE,
        TRY_TO_DATE(NAV.NAV_DATE,'YYYYMMDD') AS NAV_CALC_DATE,
        TRY_TO_NUMERIC(NAV.NET_ASSET, 38, 2) AS NET_ASSET_VALUE,
        -- NV.NAV_CHG AS NAV_CHG,
        TO_NUMERIC(NAV.NAV, 38, 4) AS NAV_PER_SHARE,
        TO_NUMERIC(NAV.NET_SHARES_OUTST, 38, 3) AS NET_CAPSTOCK_SHARES_OUTSTANDING,
        NAV.HASH_DIFF,
        NAV.LOAD_DATETIME
    FROM 
      IM_VAULT.RDV.NAV_SSB_SAT NAV   
    JOIN ACSLV ON ACSLV.STT_MCH_ACCOUNT_CODE=NAV.FUND_ID AND ACSLV.STT_MCH_BASIS_IND=NAV.BASIS_IND
    AND TO_DATE(NAV_DATE,'YYYYMMDD') BETWEEN ACSLV.FROM_DATE AND ACSLV.TO_DATE 
    
    JOIN SLV ON SLV.SLEEVE_ID=ACSLV.SLEEVE_ID
    AND TO_DATE(NAV_DATE,'YYYYMMDD') BETWEEN SLV.FROM_DATE AND SLV.TO_DATE

    UNION ALL

    SELECT DISTINCT
        SLV.SLEEVE_ID AS SLEEVE_ID,
        SLV.SLEEVE_HKEY AS SLEEVE_HKEY,
        TRY_TO_DATE(NAV.NAV_DATE,'YYYYMMDD') AS BUSINESS_DATE,
        TRY_TO_DATE(NAV.NAV_DATE,'YYYYMMDD') AS NAV_CALC_DATE,
        TRY_TO_NUMERIC(NAV.NET_ASSET, 38, 2) AS NET_ASSET_VALUE,
        TO_NUMERIC(NAV.NAV, 38, 4) AS NAV_PER_SHARE,
        TO_NUMERIC(NAV.NET_SHARES_OUTST, 38, 3) AS NET_CAPSTOCK_SHARES_OUTSTANDING,
        NAV.HASH_DIFF,
        TRY_TO_DATE(NAV.DATE_ADDED, 'YYYYMMDD') AS "LOAD_DATE"
    FROM 
      IM_VAULT_DEV.REFERENCE.NAV_MANUAL_ADD 
    JOIN ACSLV ON ACSLV.STT_MCH_ACCOUNT_CODE=NAV.FUND_ID AND ACSLV.STT_MCH_BASIS_IND=NAV.BASIS_IND
    AND TO_DATE(NAV_DATE,'YYYYMMDD') BETWEEN ACSLV.FROM_DATE AND ACSLV.TO_DATE 
    
    JOIN SLV ON SLV.SLEEVE_ID=ACSLV.SLEEVE_ID
    AND TO_DATE(NAV_DATE,'YYYYMMDD') BETWEEN SLV.FROM_DATE AND SLV.TO_DATE
),
OVR_RECORDS AS (
    SELECT *
    FROM
        (
        SELECT
             HASH_DIFF
            ,OVERRIDE_TYPE
            ,BUSINESS_DATE
            ,LOAD_DATETIME
            ,ATTRIBUTE_NAME
            ,ATTRIBUTE_VALUE
            ,ROW_NUMBER() OVER (PARTITION BY HASH_DIFF, ATTRIBUTE_NAME
                                  ORDER BY LOAD_DATETIME DESC) AS "RECORD_PRIORITY"
        FROM
            IM_VAULT_DEV.NEEDED_A_PLACE.OVERRIDE_LOOKUP
        )
    WHERE "RECORD_PRIORITY" = '1'
),
EXCLUDE_CHECK AS (
    SELECT
        OVR_R.HASH_DIFF
    FROM
        OVR_RECORDS OVR_R
    WHERE OVR_R.OVERRIDE_TYPE = 'Exclude'
),
PIVOT_OVR AS (
    SELECT
        OVR_R.HASH_DIFF
        ,MAX(CASE
             WHEN OVR_R.ATTRIBUTE_NAME = 'NAV_CALC_DATE'
             AND OVR_R.OVERRIDE_TYPE = 'Override'
             THEN OVR_R.ATTRIBUTE_VALUE END) AS OVERRIDE_NAV_CALC_DATE
        ,MAX(CASE
             WHEN OVR_R.ATTRIBUTE_NAME = 'NET_ASSET_VALUE'
             AND OVR_R.OVERRIDE_TYPE = 'Override'
             THEN OVR_R.ATTRIBUTE_VALUE END) AS OVERRIDE_NET_ASSET_VALUE
        ,MAX(CASE
             WHEN OVR_R.ATTRIBUTE_NAME = 'NAV_PER_SHARE'
             AND OVR_R.OVERRIDE_TYPE = 'Override'
             THEN OVR_R.ATTRIBUTE_VALUE END) AS OVERRIDE_NAV_PER_SHARE
        ,MAX(CASE
             WHEN OVR_R.ATTRIBUTE_NAME = 'NET_CAPSTOCK_SHARES_OUTSTANDING'
             AND OVR_R.OVERRIDE_TYPE = 'Override'
             THEN OVR_R.ATTRIBUTE_VALUE END) AS OVERRIDE_NET_CAPSTOCK_SHARES_OUTSTANDING
        ,MAX(OVR_R.LOAD_DATETIME) AS "LOAD_DATETIME"
    FROM
        OVR_RECORDS OVR_R
    WHERE OVR_R.OVERRIDE_TYPE = 'Override'
    GROUP BY OVR_R.HASH_DIFF
)
SELECT
    SNS.SLEEVE_ID AS SLEEVE_ID
    ,SNS.SLEEVE_HKEY AS SLEEVE_HKEY
    ,SNS.BUSINESS_DATE AS BUSINESS_DATE
    ,COALESCE(CASE
              WHEN OL."OVERRIDE_NAV_CALC_DATE" IS NOT NULL
              AND OL.LOAD_DATETIME > SNS.LOAD_DATETIME
              THEN OL."OVERRIDE_NAV_CALC_DATE"
              ELSE NULL
              END, SNS.NAV_CALC_DATE) AS "NAV_CALC_DATE"
    ,COALESCE(CASE
              WHEN OL."OVERRIDE_NET_ASSET_VALUE" IS NOT NULL
              AND OL.LOAD_DATETIME > SNS.LOAD_DATETIME
              THEN OL."OVERRIDE_NET_ASSET_VALUE"
              ELSE NULL
              END, SNS.NET_ASSET_VALUE) AS "NET_ASSET_VALUE"
     ,COALESCE(CASE
              WHEN OL."OVERRIDE_NAV_PER_SHARE" IS NOT NULL
              AND OL.LOAD_DATETIME > SNS.LOAD_DATETIME
              THEN OL."OVERRIDE_NAV_PER_SHARE"
              ELSE NULL
              END, SNS.NAV_PER_SHARE) AS "NAV_PER_SHARE"
     ,COALESCE(CASE
              WHEN OL."OVERRIDE_NET_CAPSTOCK_SHARES_OUTSTANDING" IS NOT NULL
              AND OL.LOAD_DATETIME > SNS.LOAD_DATETIME
              THEN OL."OVERRIDE_NET_CAPSTOCK_SHARES_OUTSTANDING"
              ELSE NULL
              END, SNS.NET_CAPSTOCK_SHARES_OUTSTANDING) AS "NET_CAPSTOCK_SHARES_OUTSTANDING"
    ,SNS.HASH_DIFF
    ,SNS.LOAD_DATETIME
FROM SLEEVE_NAV_SAT SNS
LEFT JOIN
    PIVOT_OVR OL
    ON OL.HASH_DIFF = SNS.HASH_DIFF
WHERE
    SNS.HASH_DIFF NOT IN (
        SELECT
            HASH_DIFF
        FROM
            EXCLUDE_CHECK
    )
);